### PR TITLE
Testing ad-panel

### PR DESCRIPTION
**Pull request by fabiosantoscode**
I took some tests from the old pull request, modified it and added more.

### CODE REVIEW

**Comment by keithamus** [comment]
```bash

> @economist/component-ad-panel@1.0.2 lint /Users/keith/Projects/Economist/component-ad-panel
> eslint $npm_package_config_lint_opts .

The react/jsx-quotes rule is deprecated. Please use the jsx-quotes rule instead.

/Users/keith/Projects/Economist/component-ad-panel/example.es6
  108:56  error  A space is required after '['   array-bracket-spacing
  108:57  error  A space is required after '['   array-bracket-spacing
  108:66  error  A space is required before ']'  array-bracket-spacing
  108:67  error  A space is required before ']'  array-bracket-spacing

/Users/keith/Projects/Economist/component-ad-panel/index.es6
   26:6   error  Missing semicolon                                                              semi
   50:15  error  Identifier 'useSSL' does not match the pattern '^[A-Z]?[a-z]+([A-Z][a-z]+)*$'  id-match
   50:24  error  Expected literal to be on the right side of ===                                yoda
   51:20  error  Unexpected string concatenation                                                prefer-template
   51:21  error  Identifier 'useSSL' does not match the pattern '^[A-Z]?[a-z]+([A-Z][a-z]+)*$'  id-match
   94:41  error  Missing semicolon                                                              semi
  109:44  error  Missing semicolon                                                              semi
  118:45  error  Unexpected console statement                                                   no-console
  119:9   error  Unexpected console statement                                                   no-console
  125:9   error  Variable 'tag' should be initialized on declaration                            init-declarations
  128:48  error  Unexpected use of undefined                                                    no-undefined
  128:57  error  Missing trailing comma                                                         comma-dangle
  132:9   error  `rootClassNames` is never modified, use `const` instead                        prefer-const
  132:26  error  A space is required after '['                                                  array-bracket-spacing
  132:48  error  A space is required before ']'                                                 array-bracket-spacing
  133:9   error  Variable 'title' should be initialized on declaration                          init-declarations
  136:83  error  Missing semicolon                                                              semi

✖ 21 problems (21 errors, 0 warnings)
```

**Comment by keithamus** [comment]
I suppose #18 is meant to deal with these... could you combine the two so I can test this one?

**Comment by fabiosantoscode** [comment]
Alrighty

**Comment by fabiosantoscode** [comment]
There

**Comment by keithamus** [comment]
`karma` needs to be installed as a devdep

**Comment by sebinsua** [comment]
Relating to Karma, [see also this devpack issue](https://github.com/EconomistDigitalSolutions/fe-component-devpack/pull/21) which [does not seem to be fixed in the new devpack yet](https://github.com/keithamus/fe-component-devpack/blob/new-devpack/provisioners/react-component/5.0.0/index.es6#L313-L315).

**Comment by fabiosantoscode** [comment]
There.

I do think it's best to wait for the new devpack to be ready and use it instead of manually updating these things.

**Comment by sublimino** [comment]
LGTM

**Comment by sublimino** [comment]
@keithamus @angelorepole @umbobabo can we get this merged so it can be QA'd before the demo please?

**Pull request merged**
